name: Package Python Code

on:
  repository_dispatch:
    types: [python-build]

jobs:
  register:
    runs-on: ubuntu-latest
    name: register
    steps:
      - name: Register source build
        id: source_build
        uses: veracode/github-actions-integration-helper@v0.1.8
        with:
          action: registerBuild
          token: ${{ github.event.client_payload.token }}
          appname: ${{ github.event.client_payload.user_config.profile_name }}
          source_repository: ${{ github.event.client_payload.repository.full_name }}
          check_run_id: ${{ github.run_id }}
          check_run_name: ${{ github.workflow }}
          head_sha: ${{ github.event.client_payload.sha }}
          event_type: ${{ github.event.client_payload.event_type }}
          branch: ${{ github.event.client_payload.repository.branch }}

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create ZIP package
        run: |
          zip -r python_app.zip . -x "*.git*" "__pycache__/*" "*.pytest_cache*" "dist/*"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: python_app
          path: python_app.zip
