name: Package Python Code

on:
  repository_dispatch:
    types: [python-build]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create ZIP package
        run: |
          zip -r python_app.zip . -x "*.git*" "__pycache__/*" "*.pytest_cache*" "dist/*"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: python_app
          path: python_app.zip
